### PR TITLE
Support converting asset links to references

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
### Description

Assets are different from other elements as they have their own base URL
tied to its filesystem. Put those into the matching candidates and perform
asset matching using dedicated logic.

### Related issues

N/A

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
@brandonkelly May I get a review?

**Comment by ishitatsuyuki** [comment]
Whitespace fixed.

**Comment by ishitatsuyuki** [comment]
Thank you.

**Comment by brandonkelly** [comment]
Thanks for the PR! I just released versions 1.0.8 and 2.0.4 with changes adapted from this.

**Pull request closed without merging**
